name: Make .ics file to host

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential 

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vobject requests

      - name: Run Python script
        run: |
          python -u save.py

      - name: Commit and push comicw.ics, comicw.db
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output/comicw.ics output/comicw.db
          git commit -m "Update comicw.ics, comicw.db"
          git push https://${{ secrets.GH_TOKEN }}@github.com/subculture-calendar/comicw-ics.git HEAD:main
